/***************************************************************************//**
* File Name: cycfg_bt_gatt_db.h
* Version: 1.1
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 1.1.0 build 186
*
********************************************************************************
* Copyright 2019 Cypress Semiconductor Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_BT_GATT_DB_H)
#define CYCFG_BT_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS               0x1800u
#define __UUID_CHARACTERISTIC_DEVICE_NAME           0x2A00u
#define __UUID_CHARACTERISTIC_APPEARANCE            0x2A01u
#define __UUID_SERVICE_GENERIC_ATTRIBUTE            0x1801u
#define __UUID_SERVICE_TPUT                         0xCCu, 0x7Bu, 0xCBu, 0x32u, 0x07u, 0x08u, 0x17u, 0xAFu, 0xD3u, 0x43u, 0x1Eu, 0x5Du, 0x20u, 0x0Du, 0xECu, 0x1Au
#define __UUID_CHARACTERISTIC_TPUT_NOTIFY           0x1Eu, 0x25u, 0x21u, 0x59u, 0x67u, 0x84u, 0x78u, 0x9Eu, 0x30u, 0x4Du, 0xE9u, 0x91u, 0x81u, 0x13u, 0xB0u, 0xF7u
#define __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION    0x2902u

/* Service Generic Access */
#define HDLS_GAP                                    0x0001u
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                        0x0002u
#define HDLC_GAP_DEVICE_NAME_VALUE                  0x0003u
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                         0x0004u
#define HDLC_GAP_APPEARANCE_VALUE                   0x0005u

/* Service Generic Attribute */
#define HDLS_GATT                                   0x0006u

/* Service TPUT */
#define HDLS_TPUT                                   0x0007u
/* Characteristic Notify */
#define HDLC_TPUT_NOTIFY                            0x0008u
#define HDLC_TPUT_NOTIFY_VALUE                      0x0009u
/* Descriptor Descriptor */
#define HDLD_TPUT_NOTIFY_DESCRIPTOR                 0x000Au

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_tput_notify[];
extern const uint16_t app_tput_notify_len;
extern uint8_t app_tput_notify_descriptor[];
extern const uint16_t app_tput_notify_descriptor_len;

#endif /* CYCFG_BT_GATT_DB_H */

