/***************************************************************************//**
* File Name: app_gatt_db.h
* Version: 1.1
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 1.1.0 build 96
*
********************************************************************************
* Copyright 2019, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define __UUID_SERVICE_GENERIC_ACCESS                         0x1800u
#define __UUID_CHARACTERISTIC_DEVICE_NAME                     0x2A00u
#define __UUID_CHARACTERISTIC_APPEARANCE                      0x2A01u
#define __UUID_SERVICE_GENERIC_ATTRIBUTE                      0x1801u
#define __UUID_SERVICE_HEART_RATE                             0x180Du
#define __UUID_CHARACTERISTIC_HEART_RATE_MEASUREMENT          0x2A37u
#define __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION    0x2902u
#define __UUID_CHARACTERISTIC_BODY_SENSOR_LOCATION            0x2A38u
#define __UUID_CHARACTERISTIC_HEART_RATE_CONTROL_POINT        0x2A39u
#define __UUID_SERVICE_DEVICE_INFORMATION                     0x180Au
#define __UUID_CHARACTERISTIC_MANUFACTURER_NAME_STRING        0x2A29u
#define __UUID_CHARACTERISTIC_MODEL_NUMBER_STRING             0x2A24u
#define __UUID_CHARACTERISTIC_FIRMWARE_REVISION_STRING        0x2A26u
#define __UUID_CHARACTERISTIC_SOFTWARE_REVISION_STRING        0x2A28u
#define __UUID_CHARACTERISTIC_SERIAL_NUMBER_STRING            0x2A25u
#define __UUID_CHARACTERISTIC_HARDWARE_REVISION_STRING        0x2A27u
#define __UUID_CHARACTERISTIC_SYSTEM_ID                       0x2A23u

/* Service Generic Access */
#define HDLS_GAP                                              0x0001u
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                                  0x0002u
#define HDLC_GAP_DEVICE_NAME_VALUE                            0x0003u
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                                   0x0004u
#define HDLC_GAP_APPEARANCE_VALUE                             0x0005u

/* Service Generic Attribute */
#define HDLS_GATT                                             0x0006u

/* Service Heart Rate */
#define HDLS_HRS                                              0x0007u
/* Characteristic Heart Rate Measurement */
#define HDLC_HRS_HEART_RATE_MEASUREMENT                       0x0008u
#define HDLC_HRS_HEART_RATE_MEASUREMENT_VALUE                 0x0009u
/* Descriptor Client Characteristic Configuration */
#define HDLD_HRS_HEART_RATE_MEASUREMENT_CLIENT_CHAR_CONFIG    0x000Au
/* Characteristic Body Sensor Location */
#define HDLC_HRS_BODY_SENSOR_LOCATION                         0x000Bu
#define HDLC_HRS_BODY_SENSOR_LOCATION_VALUE                   0x000Cu
/* Characteristic Heart Rate Control Point */
#define HDLC_HRS_HEART_RATE_CONTROL_POINT                     0x000Du
#define HDLC_HRS_HEART_RATE_CONTROL_POINT_VALUE               0x000Eu

/* Service Device Information */
#define HDLS_DIS                                              0x000Fu
/* Characteristic Manufacturer Name String */
#define HDLC_DIS_MANUFACTURER_NAME_STRING                     0x0010u
#define HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE               0x0011u
/* Characteristic Model Number String */
#define HDLC_DIS_MODEL_NUMBER_STRING                          0x0012u
#define HDLC_DIS_MODEL_NUMBER_STRING_VALUE                    0x0013u
/* Characteristic Firmware Revision String */
#define HDLC_DIS_FIRMWARE_REVISION_STRING                     0x0014u
#define HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE               0x0015u
/* Characteristic Software Revision String */
#define HDLC_DIS_SOFTWARE_REVISION_STRING                     0x0016u
#define HDLC_DIS_SOFTWARE_REVISION_STRING_VALUE               0x0017u
/* Characteristic Serial Number String */
#define HDLC_DIS_SERIAL_NUMBER_STRING                         0x0018u
#define HDLC_DIS_SERIAL_NUMBER_STRING_VALUE                   0x0019u
/* Characteristic Hardware Revision String */
#define HDLC_DIS_HARDWARE_REVISION_STRING                     0x001Au
#define HDLC_DIS_HARDWARE_REVISION_STRING_VALUE               0x001Bu
/* Characteristic System ID */
#define HDLC_DIS_SYSTEM_ID                                    0x001Cu
#define HDLC_DIS_SYSTEM_ID_VALUE                              0x001Du

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_hrs_heart_rate_measurement[];
extern const uint16_t app_hrs_heart_rate_measurement_len;
extern uint8_t app_hrs_heart_rate_measurement_client_char_config[];
extern const uint16_t app_hrs_heart_rate_measurement_client_char_config_len;
extern uint8_t app_hrs_body_sensor_location[];
extern const uint16_t app_hrs_body_sensor_location_len;
extern uint8_t app_hrs_heart_rate_control_point[];
extern const uint16_t app_hrs_heart_rate_control_point_len;
extern uint8_t app_dis_manufacturer_name_string[];
extern const uint16_t app_dis_manufacturer_name_string_len;
extern uint8_t app_dis_model_number_string[];
extern const uint16_t app_dis_model_number_string_len;
extern uint8_t app_dis_firmware_revision_string[];
extern const uint16_t app_dis_firmware_revision_string_len;
extern uint8_t app_dis_software_revision_string[];
extern const uint16_t app_dis_software_revision_string_len;
extern uint8_t app_dis_serial_number_string[];
extern const uint16_t app_dis_serial_number_string_len;
extern uint8_t app_dis_hardware_revision_string[];
extern const uint16_t app_dis_hardware_revision_string_len;
extern uint8_t app_dis_system_id[];
extern const uint16_t app_dis_system_id_len;

#endif /* __GATT_DATABASE_H__ */

