/***************************************************************************//**
* File Name: app_gatt_db.c
* Version: 1.1
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 1.1.0 build 96
*
********************************************************************************
* Copyright 2019, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"
#include "cycfg_gatt_db.h"

/*************************************************************************************
* GATT server definitions
*************************************************************************************/

const uint8_t gatt_database[] =
{
    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (HDLS_GAP, __UUID_SERVICE_GENERIC_ACCESS),
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16 (HDLC_GAP_DEVICE_NAME, HDLC_GAP_DEVICE_NAME_VALUE, __UUID_CHARACTERISTIC_DEVICE_NAME, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (HDLC_GAP_APPEARANCE, HDLC_GAP_APPEARANCE_VALUE, __UUID_CHARACTERISTIC_APPEARANCE, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),

    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (HDLS_GATT, __UUID_SERVICE_GENERIC_ATTRIBUTE),

    /* Primary Service: Heart Rate */
    PRIMARY_SERVICE_UUID16 (HDLS_HRS, __UUID_SERVICE_HEART_RATE),
        /* Characteristic: Heart Rate Measurement */
        CHARACTERISTIC_UUID16 (HDLC_HRS_HEART_RATE_MEASUREMENT, HDLC_HRS_HEART_RATE_MEASUREMENT_VALUE, __UUID_CHARACTERISTIC_HEART_RATE_MEASUREMENT, LEGATTDB_CHAR_PROP_NOTIFY, LEGATTDB_PERM_NONE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_HRS_HEART_RATE_MEASUREMENT_CLIENT_CHAR_CONFIG, __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Body Sensor Location */
        CHARACTERISTIC_UUID16 (HDLC_HRS_BODY_SENSOR_LOCATION, HDLC_HRS_BODY_SENSOR_LOCATION_VALUE, __UUID_CHARACTERISTIC_BODY_SENSOR_LOCATION, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Heart Rate Control Point */
        CHARACTERISTIC_UUID16_WRITABLE (HDLC_HRS_HEART_RATE_CONTROL_POINT, HDLC_HRS_HEART_RATE_CONTROL_POINT_VALUE, __UUID_CHARACTERISTIC_HEART_RATE_CONTROL_POINT, LEGATTDB_CHAR_PROP_WRITE, LEGATTDB_PERM_WRITE_REQ),

    /* Primary Service: Device Information */
    PRIMARY_SERVICE_UUID16 (HDLS_DIS, __UUID_SERVICE_DEVICE_INFORMATION),
        /* Characteristic: Manufacturer Name String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_MANUFACTURER_NAME_STRING, HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE, __UUID_CHARACTERISTIC_MANUFACTURER_NAME_STRING, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Model Number String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_MODEL_NUMBER_STRING, HDLC_DIS_MODEL_NUMBER_STRING_VALUE, __UUID_CHARACTERISTIC_MODEL_NUMBER_STRING, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Firmware Revision String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_FIRMWARE_REVISION_STRING, HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE, __UUID_CHARACTERISTIC_FIRMWARE_REVISION_STRING, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Software Revision String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_SOFTWARE_REVISION_STRING, HDLC_DIS_SOFTWARE_REVISION_STRING_VALUE, __UUID_CHARACTERISTIC_SOFTWARE_REVISION_STRING, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Serial Number String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_SERIAL_NUMBER_STRING, HDLC_DIS_SERIAL_NUMBER_STRING_VALUE, __UUID_CHARACTERISTIC_SERIAL_NUMBER_STRING, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Hardware Revision String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_HARDWARE_REVISION_STRING, HDLC_DIS_HARDWARE_REVISION_STRING_VALUE, __UUID_CHARACTERISTIC_HARDWARE_REVISION_STRING, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: System ID */
        CHARACTERISTIC_UUID16 (HDLC_DIS_SYSTEM_ID, HDLC_DIS_SYSTEM_ID_VALUE, __UUID_CHARACTERISTIC_SYSTEM_ID, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);

/*************************************************************************************
 * GATT Initial Value Arrays
 ************************************************************************************/

uint8_t app_gap_device_name[]                               = {'H', 'R', 'S', };
uint8_t app_gap_appearance[]                                = {0x00u, 0x02u, };
uint8_t app_hrs_heart_rate_measurement[]                    = {0x00u, 0x00u, };
uint8_t app_hrs_heart_rate_measurement_client_char_config[] = {0x00u, 0x00u, };
uint8_t app_hrs_body_sensor_location[]                      = {0x00u, };
uint8_t app_hrs_heart_rate_control_point[]                  = {0x01u, };
uint8_t app_dis_manufacturer_name_string[]                  = {'C', 'y', 'p', 'r', 'e', 's', 's', };
uint8_t app_dis_model_number_string[]                       = {'B', 'L', 'E', '2', '0', '8', '1', '9', };
uint8_t app_dis_firmware_revision_string[]                  = {'1', '0', '1', };
uint8_t app_dis_software_revision_string[]                  = {'1', '0', '2', };
uint8_t app_dis_serial_number_string[]                      = {'1', '0', '3', };
uint8_t app_dis_hardware_revision_string[]                  = {'1', '0', '4', };
uint8_t app_dis_system_id[]                                 = {0x69u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, };

 /************************************************************************************
 * GATT Lookup Table
 ************************************************************************************/

gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    /* { attribute handle,                                maxlen, curlen, attribute data } */
    { HDLC_GAP_DEVICE_NAME_VALUE,                         3,      3,      app_gap_device_name },
    { HDLC_GAP_APPEARANCE_VALUE,                          2,      2,      app_gap_appearance },
    { HDLC_HRS_HEART_RATE_MEASUREMENT_VALUE,              2,      2,      app_hrs_heart_rate_measurement },
    { HDLD_HRS_HEART_RATE_MEASUREMENT_CLIENT_CHAR_CONFIG, 2,      2,      app_hrs_heart_rate_measurement_client_char_config },
    { HDLC_HRS_BODY_SENSOR_LOCATION_VALUE,                1,      1,      app_hrs_body_sensor_location },
    { HDLC_HRS_HEART_RATE_CONTROL_POINT_VALUE,            1,      1,      app_hrs_heart_rate_control_point },
    { HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE,            7,      7,      app_dis_manufacturer_name_string },
    { HDLC_DIS_MODEL_NUMBER_STRING_VALUE,                 8,      8,      app_dis_model_number_string },
    { HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE,            3,      3,      app_dis_firmware_revision_string },
    { HDLC_DIS_SOFTWARE_REVISION_STRING_VALUE,            3,      3,      app_dis_software_revision_string },
    { HDLC_DIS_SERIAL_NUMBER_STRING_VALUE,                3,      3,      app_dis_serial_number_string },
    { HDLC_DIS_HARDWARE_REVISION_STRING_VALUE,            3,      3,      app_dis_hardware_revision_string },
    { HDLC_DIS_SYSTEM_ID_VALUE,                           8,      8,      app_dis_system_id },
};

/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size = (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = (sizeof(app_gap_device_name));
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_hrs_heart_rate_measurement_len = (sizeof(app_hrs_heart_rate_measurement));
const uint16_t app_hrs_heart_rate_measurement_client_char_config_len = (sizeof(app_hrs_heart_rate_measurement_client_char_config));
const uint16_t app_hrs_body_sensor_location_len = (sizeof(app_hrs_body_sensor_location));
const uint16_t app_hrs_heart_rate_control_point_len = (sizeof(app_hrs_heart_rate_control_point));
const uint16_t app_dis_manufacturer_name_string_len = (sizeof(app_dis_manufacturer_name_string));
const uint16_t app_dis_model_number_string_len = (sizeof(app_dis_model_number_string));
const uint16_t app_dis_firmware_revision_string_len = (sizeof(app_dis_firmware_revision_string));
const uint16_t app_dis_software_revision_string_len = (sizeof(app_dis_software_revision_string));
const uint16_t app_dis_serial_number_string_len = (sizeof(app_dis_serial_number_string));
const uint16_t app_dis_hardware_revision_string_len = (sizeof(app_dis_hardware_revision_string));
const uint16_t app_dis_system_id_len = (sizeof(app_dis_system_id));

