/***************************************************************************//**
* File Name: app_gatt_db.c
* Version: 1.1
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 1.1.0 build 89
*
********************************************************************************
* Copyright 2019, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"
#include "cycfg_gatt_db.h"

/*************************************************************************************
* GATT server definitions
*************************************************************************************/

const uint8_t gatt_database[] =
{
    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (HDLS_GAP, __UUID_SERVICE_GENERIC_ACCESS),
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16 (HDLC_GAP_DEVICE_NAME, HDLC_GAP_DEVICE_NAME_VALUE, __UUID_CHARACTERISTIC_DEVICE_NAME, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_AUTH_READABLE),
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (HDLC_GAP_APPEARANCE, HDLC_GAP_APPEARANCE_VALUE, __UUID_CHARACTERISTIC_APPEARANCE, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_AUTH_READABLE),

    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (HDLS_GATT, __UUID_SERVICE_GENERIC_ATTRIBUTE),

    /* Primary Service: Battery */
    PRIMARY_SERVICE_UUID16 (HDLS_BAS, __UUID_SERVICE_BATTERY),
        /* Characteristic: Battery Level */
        CHARACTERISTIC_UUID16 (HDLC_BAS_BATTERY_LEVEL, HDLC_BAS_BATTERY_LEVEL_VALUE, __UUID_CHARACTERISTIC_BATTERY_LEVEL, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_AUTH_READABLE),

    /* Primary Service: Device Information */
    PRIMARY_SERVICE_UUID16 (HDLS_DIS, __UUID_SERVICE_DEVICE_INFORMATION),
        /* Characteristic: Manufacturer Name String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_MANUFACTURER_NAME_STRING, HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE, __UUID_CHARACTERISTIC_MANUFACTURER_NAME_STRING, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Model Number String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_MODEL_NUMBER_STRING, HDLC_DIS_MODEL_NUMBER_STRING_VALUE, __UUID_CHARACTERISTIC_MODEL_NUMBER_STRING, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Firmware Revision String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_FIRMWARE_REVISION_STRING, HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE, __UUID_CHARACTERISTIC_FIRMWARE_REVISION_STRING, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_AUTH_READABLE),
        /* Characteristic: Software Revision String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_SOFTWARE_REVISION_STRING, HDLC_DIS_SOFTWARE_REVISION_STRING_VALUE, __UUID_CHARACTERISTIC_SOFTWARE_REVISION_STRING, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_AUTH_READABLE),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);

/*************************************************************************************
 * GATT Initial Value Arrays
 ************************************************************************************/

uint8_t app_gap_device_name[]              = {'W', 'a', 't', 'c', 'h', };
uint8_t app_gap_appearance[]               = {0xC1u, 0x00u, };
uint8_t app_bas_battery_level[]            = {0x64u, };
uint8_t app_dis_manufacturer_name_string[] = {'C', 'y', 'p', 'r', 'e', 's', 's', };
uint8_t app_dis_model_number_string[]      = {'B', 'L', 'E', '2', '0', '8', '1', '9', };
uint8_t app_dis_firmware_revision_string[] = {'B', 'L', 'E', '2', '0', '8', '1', '9', };
uint8_t app_dis_software_revision_string[] = {'1', '1', };

 /************************************************************************************
 * GATT Lookup Table
 ************************************************************************************/

gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    /* { attribute handle,               maxlen, curlen, attribute data } */
    { HDLC_GAP_DEVICE_NAME_VALUE,        5,      5,      app_gap_device_name },
    { HDLC_GAP_APPEARANCE_VALUE,         2,      2,      app_gap_appearance },
    { HDLC_BAS_BATTERY_LEVEL_VALUE,      1,      1,      app_bas_battery_level },
    { HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE, 7,      7,      app_dis_manufacturer_name_string },
    { HDLC_DIS_MODEL_NUMBER_STRING_VALUE, 8,      8,      app_dis_model_number_string },
    { HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE, 8,      8,      app_dis_firmware_revision_string },
    { HDLC_DIS_SOFTWARE_REVISION_STRING_VALUE, 2,      2,      app_dis_software_revision_string },
};

/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size = (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = (sizeof(app_gap_device_name));
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_bas_battery_level_len = (sizeof(app_bas_battery_level));
const uint16_t app_dis_manufacturer_name_string_len = (sizeof(app_dis_manufacturer_name_string));
const uint16_t app_dis_model_number_string_len = (sizeof(app_dis_model_number_string));
const uint16_t app_dis_firmware_revision_string_len = (sizeof(app_dis_firmware_revision_string));
const uint16_t app_dis_software_revision_string_len = (sizeof(app_dis_software_revision_string));

