/***************************************************************************//**
* File Name: app_gatt_db.c
* Version: 1.1
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 1.1.0 build 89
*
********************************************************************************
* Copyright 2019, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"
#include "cycfg_gatt_db.h"

/*************************************************************************************
* GATT server definitions
*************************************************************************************/

const uint8_t gatt_database[] =
{
    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (HDLS_GAP, __UUID_SERVICE_GENERIC_ACCESS),
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16 (HDLC_GAP_DEVICE_NAME, HDLC_GAP_DEVICE_NAME_VALUE, __UUID_CHARACTERISTIC_DEVICE_NAME, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (HDLC_GAP_APPEARANCE, HDLC_GAP_APPEARANCE_VALUE, __UUID_CHARACTERISTIC_APPEARANCE, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),

    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (HDLS_GATT, __UUID_SERVICE_GENERIC_ATTRIBUTE),

    /* Primary Service: Alert Notification */
    PRIMARY_SERVICE_UUID16 (HDLS_ANS, __UUID_SERVICE_ALERT_NOTIFICATION),
        /* Characteristic: Supported New Alert Category */
        CHARACTERISTIC_UUID16 (HDLC_ANS_SUPPORTED_NEW_ALERT_CATEGORY, HDLC_ANS_SUPPORTED_NEW_ALERT_CATEGORY_VALUE, __UUID_CHARACTERISTIC_SUPPORTED_NEW_ALERT_CATEGORY, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: New Alert */
        CHARACTERISTIC_UUID16 (HDLC_ANS_NEW_ALERT, HDLC_ANS_NEW_ALERT_VALUE, __UUID_CHARACTERISTIC_NEW_ALERT, LEGATTDB_CHAR_PROP_NOTIFY, LEGATTDB_PERM_NONE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_ANS_NEW_ALERT_CLIENT_CHAR_CONFIG, __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Supported Unread Alert Category */
        CHARACTERISTIC_UUID16 (HDLC_ANS_SUPPORTED_UNREAD_ALERT_CATEGORY, HDLC_ANS_SUPPORTED_UNREAD_ALERT_CATEGORY_VALUE, __UUID_CHARACTERISTIC_SUPPORTED_UNREAD_ALERT_CATEGORY, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Unread Alert Status */
        CHARACTERISTIC_UUID16 (HDLC_ANS_UNREAD_ALERT_STATUS, HDLC_ANS_UNREAD_ALERT_STATUS_VALUE, __UUID_CHARACTERISTIC_UNREAD_ALERT_STATUS, LEGATTDB_CHAR_PROP_NOTIFY, LEGATTDB_PERM_NONE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_ANS_UNREAD_ALERT_STATUS_CLIENT_CHAR_CONFIG, __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Alert Notification Control Point */
        CHARACTERISTIC_UUID16_WRITABLE (HDLC_ANS_ALERT_NOTIFICATION_CONTROL_POINT, HDLC_ANS_ALERT_NOTIFICATION_CONTROL_POINT_VALUE, __UUID_CHARACTERISTIC_ALERT_NOTIFICATION_CONTROL_POINT, LEGATTDB_CHAR_PROP_WRITE, LEGATTDB_PERM_WRITE_REQ),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);

/*************************************************************************************
 * GATT Initial Value Arrays
 ************************************************************************************/

uint8_t app_gap_device_name[]                            = {'A', 'N', 'C', };
uint8_t app_gap_appearance[]                             = {0x00u, 0x02u, };
uint8_t app_ans_supported_new_alert_category[]           = {0x00u, 0x00u, };
uint8_t app_ans_new_alert[]                              = {0x00u, 0x00u, };
uint8_t app_ans_new_alert_client_char_config[]           = {0x00u, 0x00u, };
uint8_t app_ans_supported_unread_alert_category[]        = {0x00u, 0x00u, };
uint8_t app_ans_unread_alert_status[]                    = {0x00u, 0x00u, };
uint8_t app_ans_unread_alert_status_client_char_config[] = {0x00u, 0x00u, };
uint8_t app_ans_alert_notification_control_point[]       = {0x00u, 0x00u, };

 /************************************************************************************
 * GATT Lookup Table
 ************************************************************************************/

gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    /* { attribute handle,                             maxlen, curlen, attribute data } */
    { HDLC_GAP_DEVICE_NAME_VALUE,                      3,      3,      app_gap_device_name },
    { HDLC_GAP_APPEARANCE_VALUE,                       2,      2,      app_gap_appearance },
    { HDLC_ANS_SUPPORTED_NEW_ALERT_CATEGORY_VALUE,     2,      2,      app_ans_supported_new_alert_category },
    { HDLC_ANS_NEW_ALERT_VALUE,                        2,      2,      app_ans_new_alert },
    { HDLD_ANS_NEW_ALERT_CLIENT_CHAR_CONFIG,           2,      2,      app_ans_new_alert_client_char_config },
    { HDLC_ANS_SUPPORTED_UNREAD_ALERT_CATEGORY_VALUE,  2,      2,      app_ans_supported_unread_alert_category },
    { HDLC_ANS_UNREAD_ALERT_STATUS_VALUE,              2,      2,      app_ans_unread_alert_status },
    { HDLD_ANS_UNREAD_ALERT_STATUS_CLIENT_CHAR_CONFIG, 2,      2,      app_ans_unread_alert_status_client_char_config },
    { HDLC_ANS_ALERT_NOTIFICATION_CONTROL_POINT_VALUE, 2,      2,      app_ans_alert_notification_control_point },
};

/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size = (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = (sizeof(app_gap_device_name));
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_ans_supported_new_alert_category_len = (sizeof(app_ans_supported_new_alert_category));
const uint16_t app_ans_new_alert_len = (sizeof(app_ans_new_alert));
const uint16_t app_ans_new_alert_client_char_config_len = (sizeof(app_ans_new_alert_client_char_config));
const uint16_t app_ans_supported_unread_alert_category_len = (sizeof(app_ans_supported_unread_alert_category));
const uint16_t app_ans_unread_alert_status_len = (sizeof(app_ans_unread_alert_status));
const uint16_t app_ans_unread_alert_status_client_char_config_len = (sizeof(app_ans_unread_alert_status_client_char_config));
const uint16_t app_ans_alert_notification_control_point_len = (sizeof(app_ans_alert_notification_control_point));

